1. Database overview

2. Data quality assessment
   - inactive stores
   - unrealistic rentals
   - suspicious records

3. Inventory analysis

4. Rental analysis

5. Customer analysis

6. Revenue analysis

7. Conclusions

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "postgresql+psycopg2://postgres:i49as28kdG@localhost:5432/pagila"
)

## 3. Inventory analysis

In [3]:
query = """
SELECT 
	address.address AS Store_Address,
	store.store_id  AS Store_ID,
	COUNT(inventory.inventory_id) AS Inventory_Count
FROM store

LEFT JOIN inventory
ON store.store_id = inventory.store_id

LEFT JOIN address
ON store.address_id = address.address_id

GROUP BY address.address_id,store.store_id
ORDER BY Inventory_Count DESC;

"""

In [4]:
df = pd.read_sql(query, engine)
df

             store_address  store_id  inventory_count
0           478 Joliet Way         2             2311
1        569 Baicheng Lane         1             2270
2         949 Allende Lane       473                0
3         486 Ondo Parkway       489                0
4      1405 Chisinau Place       267                0
..                     ...       ...              ...
495         1515 Korla Way       359                0
496   1411 Lillydale Drive        58                0
497  1052 Pathankot Avenue       459                0
498     1386 Yangor Avenue        10                0
499        983 Santa F Way       421                0

[500 rows x 3 columns]

In [5]:
query = """
SELECT
	l.name,
	COUNT(inventory.inventory_id) AS Language_Copies,
	ROUND((100.0 * COUNT(inventory.inventory_id) / (SELECT COUNT(inventory_id) FROM inventory)),2) AS Language_Percentage
FROM "language" l

LEFT JOIN film
	ON l.language_id = film.language_id

LEFT JOIN inventory
	ON film.film_id = inventory.film_id

GROUP BY l.name;
"""

In [6]:
df = pd.read_sql(query, engine)
df

       name  language_copies  language_percentage
0   English             2735                59.70
1  Japanese              317                 6.92
2    German              380                 8.30
3  Mandarin              405                 8.84
4    French              371                 8.10
5   Italian              373                 8.14

In [7]:
query = """
SELECT
	l.name AS Language,
	COUNT(DISTINCT inventory.inventory_id) AS Language_Copies,
	ROUND((100.0 * COUNT( DISTINCT inventory.inventory_id) / (SELECT COUNT(inventory_id) FROM inventory)),2) AS Language_Percentage,
	SUM(payment.amount) AS Revenue,
	ROUND((100.0 * SUM(payment.amount) / (SELECT SUM(amount) FROM payment)),2) AS Revenue_Percentage,
	COUNT(DISTINCT rental.rental_id) AS Amount_Of_Rants,
	ROUND((100.0 * COUNT(DISTINCT rental.rental_id) / (SELECT COUNT(rental_id) FROM rental)),2) AS Rental_Percentage
FROM "language" l

LEFT JOIN film
	ON l.language_id = film.language_id

LEFT JOIN inventory
	ON film.film_id = inventory.film_id

LEFT JOIN rental
	ON inventory.inventory_id = rental.inventory_id

LEFT JOIN payment
	ON rental.rental_id = payment.rental_id

GROUP BY l.language_id;
"""

In [8]:
df = pd.read_sql(query, engine)
df

,language,language_copies,language_percentage,revenue,revenue_percentage,amount_of_rants,rental_percentage
0,English,2735,59.70,99874.25,58.42,30929,59.70
1,Italian,373,8.14,13108.26,7.67,4231,8.17
2,Japanese,317,6.92,12457.28,7.29,3528,6.81
3,Mandarin,405,8.84,16092.06,9.41,4554,8.79
4,French,371,8.10,13438.07,7.86,4151,8.01
5,German,380,8.30,15992.47,9.35,4412,8.52

--each movie missing with amount and sum of replacement cost

In [9]:
query = """
SELECT 
	film.title AS Movie,
	COUNT(film.film_id) AS Number_Of_Missing,
	SUM(film.replacement_cost) AS Replacement_Cost
FROM rental

INNER JOIN inventory
	ON rental.inventory_id = inventory.inventory_id

INNER JOIN film
	ON inventory.film_id = film.film_id



WHERE rental.return_date IS NULL
GROUP BY film.film_id
ORDER BY Number_Of_Missing DESC;"""

In [10]:
df = pd.read_sql(query, engine)
df

                    movie  number_of_missing  replacement_cost
0           CLUB GRAFFITI                  3             38.97
1           GUNFIGHT MOON                  2             33.98
2           HALF OUTFIELD                  2             51.98
3         INSIDER ARIZONA                  2             35.98
4       INTENTIONS EMPIRE                  2             27.98
..                    ...                ...               ...
210         BOOGIE AMELIE                  1             11.99
211         BOULEVARD MOB                  1             11.99
212         BOUND CHEAPER                  1             17.99
213  BREAKFAST GOLDFINGER                  1             18.99
214   BROTHERHOOD BLANKET                  1             26.99

[215 rows x 3 columns]

## 4. Rental analysis

In [11]:
query = """
SELECT 
	rental.rental_date,
	film.title,
	address.address,
	CONCAT(staff.first_name || ' ' || staff.last_name) AS Staff_Member,
	CONCAT(customer.first_name || ' ' || customer.last_name) AS Customer
FROM rental

LEFT JOIN inventory
	ON rental.inventory_id = inventory.inventory_id

LEFT JOIN film
	ON inventory.film_id = film.film_id

INNER JOIN staff
	ON rental.staff_id = staff.staff_id

INNER JOIN customer
	ON rental.customer_id = customer.customer_id

INNER JOIN store
	ON inventory.store_id = store.store_id

INNER JOIN address
ON store.address_id = address.address_id

WHERE return_date IS NULL
ORDER BY rental.rental_date ASC;
"""

In [12]:
df = pd.read_sql(query, engine)
df

,rental_date,title,address,staff_member,customer
0,2022-02-14 17:16:03+02:00,SLEEPLESS MONSOON,569 Baicheng Lane,Warner Hudson,ALICIA MILLS
1,2022-02-14 17:16:03+02:00,SEABISCUIT PUNK,478 Joliet Way,Warner Hudson,TRAVIS ESTEP
2,2022-02-14 17:16:03+02:00,SEATTLE EXPECATIONS,478 Joliet Way,Warner Hudson,LUCY WHEELER
3,2022-02-14 17:16:03+02:00,SMOOCHY CONTROL,478 Joliet Way,Lavone O'Reilly,RAYMOND MCWHORTER
4,2022-02-14 17:16:03+02:00,SHAWSHANK BUBBLE,569 Baicheng Lane,Lavone O'Reilly,VIOLA HANSON
...,...,...,...,...,...
236,2026-07-27 12:29:05.894069+03:00,MUSCLE BRIGHT,569 Baicheng Lane,Warner Hudson,SUSAN WILSON
237,2026-07-27 18:17:04.086487+03:00,WONDERLAND CHRISTMAS,569 Baicheng Lane,Lavone O'Reilly,MARY KIM
238,2026-07-27 19:12:39.377683+03:00,LOATHING LEGALLY,478 Joliet Way,Lavone O'Reilly,DAVID ROSSI
239,2026-07-27 21:19:13.640597+03:00,ALADDIN CALENDAR,569 Baicheng Lane,Warner Hudson,JACOB LANCE
240,2026-07-28 00:22:13.614736+03:00,MUMMY CREATURES,478 Joliet Way,Warner Hudson,CHESTER BENNER

--rents by month

In [13]:
query = """
SELECT 
	DATE_TRUNC('month', rental_date) AS Rent_Month,
	COUNT(rental_id) AS Amount
FROM rental

GROUP BY DATE_TRUNC('month', rental_date)
ORDER BY Rent_Month;
"""

In [14]:
df = pd.read_sql(query, engine)
df

                   rent_month  amount
0   2022-02-01 00:00:00+02:00     182
1   2022-05-01 00:00:00+03:00    1153
2   2022-06-01 00:00:00+03:00    2314
3   2022-07-01 00:00:00+03:00    6665
4   2022-08-01 00:00:00+03:00    5934
5   2022-09-01 00:00:00+03:00     725
6   2022-10-01 00:00:00+03:00     725
7   2022-11-01 00:00:00+02:00     761
8   2022-12-01 00:00:00+02:00     806
9   2023-01-01 00:00:00+02:00     731
10  2023-02-01 00:00:00+02:00     728
11  2023-03-01 00:00:00+02:00     745
12  2023-04-01 00:00:00+03:00     753
13  2023-05-01 00:00:00+03:00     746
14  2023-06-01 00:00:00+03:00     728
15  2023-07-01 00:00:00+03:00     771
16  2023-08-01 00:00:00+03:00     770
17  2023-09-01 00:00:00+03:00     747
18  2023-10-01 00:00:00+03:00     766
19  2023-11-01 00:00:00+02:00     752
20  2023-12-01 00:00:00+02:00     822
21  2024-01-01 00:00:00+02:00     797
22  2024-02-01 00:00:00+02:00     781
23  2024-03-01 00:00:00+02:00     751
24  2024-04-01 00:00:00+03:00     778
25  2024-05-01 00:00:00+03:00     818
26  2024-06-01 00:00:00+03:00     774
27  2024-07-01 00:00:00+03:00     746
28  2024-08-01 00:00:00+03:00     745
29  2024-09-01 00:00:00+03:00     629
30  2024-10-01 00:00:00+03:00     808
31  2024-11-01 00:00:00+02:00     769
32  2024-12-01 00:00:00+02:00     700
33  2025-01-01 00:00:00+02:00     768
34  2025-02-01 00:00:00+02:00     698
35  2025-03-01 00:00:00+02:00     734
36  2025-04-01 00:00:00+03:00     759
37  2025-05-01 00:00:00+03:00     802
38  2025-06-01 00:00:00+03:00     799
39  2025-07-01 00:00:00+03:00     798
40  2025-08-01 00:00:00+03:00     829
41  2025-09-01 00:00:00+03:00     680
42  2025-10-01 00:00:00+03:00     796
43  2025-11-01 00:00:00+02:00     691
44  2025-12-01 00:00:00+02:00     737
45  2026-01-01 00:00:00+02:00     779
46  2026-02-01 00:00:00+02:00     727
47  2026-03-01 00:00:00+02:00     834
48  2026-04-01 00:00:00+03:00     687
49  2026-05-01 00:00:00+03:00     812
50  2026-06-01 00:00:00+03:00     747
51  2026-07-01 00:00:00+03:00     708

## 5. Customer analysis

In [15]:
query = """
SELECT
	category.name AS Movie_Category,
	COUNT(DISTINCT film.film_id) AS Movie_Count,
	COUNT(DISTINCT inventory.inventory_id) AS Copies_for_Rent,
	COUNT(DISTINCT rental.rental_id) AS Rent_Count,
	SUM(payment.amount) AS Earned
FROM category

LEFT JOIN film_category
	ON category.category_id = film_category.category_id

LEFT JOIN film
	ON film_category.film_id = film.film_id

LEFT JOIN inventory
	ON film.film_id = inventory.film_id

LEFT JOIN rental
	ON inventory.inventory_id = rental.inventory_id

LEFT JOIN payment
	ON rental.rental_id = payment.rental_id

GROUP BY category.name
ORDER BY Earned DESC;
"""

In [16]:
df = pd.read_sql(query, engine)
df

   movie_category  movie_count  copies_for_rent  rent_count    earned
0          Action          149              688        7670  26505.44
1       Animation          148              670        7565  26460.31
2        Children          150              687        7721  26399.88
3         Foreign          150              695        7903  26387.22
4     Documentary          145              699        7976  26078.46
5           Music          152              681        7766  26036.49
6          Sci-Fi          149              710        8007  25944.08
7          Sports          145              656        7484  25583.19
8             New          147              719        8088  25403.41
9          Horror          142              639        7315  25241.89
10          Games          150              684        7802  25132.16
11         Travel          151              686        7739  24934.43
12       Classics          147              667        7478  24390.25
13          Drama          152              662        7435  23757.57
14         Family          147              683        7671  23714.46
15         Comedy          143              622        7046  23131.48

In [17]:
query = """
SELECT
	CONCAT(customer.first_name || ' ' || customer.last_name) AS Customer_Name,
	COUNT (rental.rental_id) AS Rents_Amount,
	SUM(payment.amount) AS Revenue
FROM customer

LEFT JOIN rental
	ON customer.customer_id = rental.customer_id

LEFT JOIN payment
	ON rental.rental_id = payment.rental_id

GROUP BY customer.customer_id
ORDER BY Rents_Amount DESC;
"""

In [18]:
df = pd.read_sql(query, engine)
df

         customer_name  rents_amount  revenue
0      RUSSELL BRINSON            97   324.04
1     LEROY BUSTAMANTE            95   283.07
2             TIM CARY            94   344.06
3          CURTIS IRBY            91   317.10
4             MAX PITT            90   320.11
..                 ...           ...      ...
994           WEI HALL             1     4.99
995     OLIVIER NGUYEN             1     2.99
996        KAREN ROSSI             1     2.99
997        SOFIA BAKER             0      NaN
998  JENNIFER MITCHELL             0      NaN

[999 rows x 3 columns]

--percentages of people returning rented movies in time

In [19]:
query = """
SELECT 
	CONCAT(customer.first_name || ' ' || customer.last_name) AS Customer_Name,
	COUNT (rental.rental_id) AS Rents_Amount,
	SUM(CASE
			WHEN rental.return_date IS NOT NULL AND
			((EXTRACT(EPOCH FROM (rental.return_date - rental.rental_date))) / 86400) <= film.rental_duration THEN 1
			ELSE 0
		END) AS In_Time,
	
	ROUND((SUM(CASE
			WHEN rental.return_date IS NOT NULL AND
			((EXTRACT(EPOCH FROM (rental.return_date - rental.rental_date))) / 86400) <= film.rental_duration THEN 1
			ELSE 0
		END)) * 100.0 / NULLIF(COUNT(rental.rental_id), 0),2) AS Percentage_In_Time
FROM customer

LEFT JOIN rental
ON customer.customer_id = rental.customer_id

LEFT JOIN inventory
ON rental.inventory_id = inventory.inventory_id

LEFT JOIN film
ON inventory.film_id = film.film_id

GROUP BY customer.customer_id
ORDER BY Percentage_In_Time DESC;
"""

In [20]:
df = pd.read_sql(query, engine)
df

         customer_name  rents_amount  in_time  percentage_in_time
0    JENNIFER MITCHELL             0        0                 NaN
1          SOFIA BAKER             0        0                 NaN
2          YUKI WRIGHT             2        2               100.0
3        JOSEPH THOMAS             3        3               100.0
4          KAREN ROSSI             1        1               100.0
..                 ...           ...      ...                 ...
994       SOFIA RIVERA             6        0                 0.0
995       EMILY THOMAS             1        0                 0.0
996        AHMED YOUNG             2        0                 0.0
997       CAMILA DAVIS             3        0                 0.0
998        MATEO LEWIS             2        0                 0.0

[999 rows x 4 columns]

## 6. Revenue analysis

### actors that bring the most money

In [21]:
query = """
SELECT
	CONCAT(actor.first_name || ' ' || actor.last_name) AS Actor_Name,
	COUNT(DISTINCT film.film_id) AS Movies_Featured,
	SUM(payment.amount) AS Revenue_of_Featured_Movies,
	SUM(payment.amount)/COUNT(DISTINCT film.film_id) AS Average_Revenue_per_Movie
FROM actor

LEFT JOIN film_actor
	ON actor.actor_id = film_actor.actor_id

INNER JOIN film
	ON film_actor.film_id = film.film_id

LEFT JOIN inventory
	ON film.film_id = inventory.film_id

LEFT JOIN rental 
	ON inventory.inventory_id = rental.inventory_id

LEFT JOIN payment
	ON rental.rental_id = payment.rental_id

GROUP BY actor.actor_id
ORDER BY Revenue_of_Featured_Movies DESC;
"""

In [22]:
df = pd.read_sql(query, engine)
df

,actor_name,movies_featured,revenue_of_featured_movies,average_revenue_per_movie
0,GINA DEGENERES,42,8779.08,209.025714
1,MATTHEW CARREY,39,7326.83,187.867436
2,HENRY BERRY,35,6874.45,196.412857
3,SCARLETT DAMON,36,6783.77,188.438056
4,ANGELA WITHERSPOON,35,6709.86,191.710286
...,...,...,...,...
195,SANDRA PECK,19,2575.46,135.550526
196,ADAM GRANT,18,2546.01,141.445000
197,EMILY DEE,14,2530.04,180.717143
198,SISSY SOBIESKI,18,2429.13,134.951667
199,JUDY DEAN,15,2372.97,158.198000